// 98_versus_realtime_sync.js - host-authoritative image stream + guest input + cs latency
(function(){
"use strict";
const R={mode:null,side:null,frameSeq:0,inputSeq:0,lastFrame:0,frameTimer:0,probeTimer:0,probeMap:new Map(),img:new Image(),capture:null};
const $=id=>document.getElementById(id),send=o=>window.s7WSSend?.(o);
function meter(cs){const m=$('versusLatencyMeter');$('#versusLatencyCs').textContent=Number.isFinite(cs)?`${Math.round(cs)} cs`:'-- cs';m?.classList.toggle('warn',cs>=15&&cs<30);m?.classList.toggle('bad',cs>=30)}
function roleText(side,host){$('#versusRealtimeRole').textContent=`${side==='plant'?'🌱 植物方':'🧟 僵尸方'} · ${host?'房主':'房客'}`;$('#versusRealtimeAuthority').textContent=host?'本机是唯一权威战斗计算':'只接收房主画面 · 操作发送到房主'}
function startHost(side){stop();R.mode='host';R.side=side;const room=window.S7VersusOnline?.getRoom?.();R.frameSeq=(room?.versus?.battleSeq||0);roleText(side,true);const rt=$('versusRealtimeScreen');rt?.classList.add('hidden');R.capture=document.createElement('canvas');R.capture.width=640;R.capture.height=360;R.frameTimer=setInterval(capture,100)}
function capture(){if(R.mode!=='host'||!window.S7VersusBattle?.state?.active)return;try{const c=R.capture,x=canvas;c.getContext('2d').drawImage(x,0,0,c.width,c.height);let data=c.toDataURL('image/webp',.22);if(data.length>55000)data=c.toDataURL('image/jpeg',.20);if(data.length>55000)return;send({type:'versusFrame',seq:++R.frameSeq,data})}catch(_){} }
function startGuest(side){stop();R.mode='guest';R.side=side;R.inputSeq=0;roleText(side,false);$('versusStreamPlaceholder')?.classList.remove('hidden');R.probeTimer=setInterval(probe,1000);probe()}
function probe(){if(R.mode!=='guest')return;const id=Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6),sentAt=performance.now();R.probeMap.set(id,sentAt);send({type:'versusProbe',probeId:id,sentAt})}
function drawFrame(data){if(R.mode!=='guest'||!data)return;const out=$('versusGuestStreamCanvas'),g=out?.getContext('2d');if(!g)return;R.img.onload=()=>{g.clearRect(0,0,out.width,out.height);g.drawImage(R.img,0,0,out.width,out.height);$('versusStreamPlaceholder')?.classList.add('hidden')};R.img.src=data}
function sendPointer(ev){if(R.mode!=='guest')return;const c=$('versusGuestStreamCanvas'),r=c.getBoundingClientRect();const nx=Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),ny=Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height));send({type:'versusInput',seq:++R.inputSeq,action:{kind:'pointer',nx,ny}})}
function sendKey(ev){if(R.mode!=='guest')return;const k=ev.key;if(!/^[1-7qQvV]$/.test(k))return;send({type:'versusInput',seq:++R.inputSeq,action:{kind:'key',key:k}});ev.preventDefault()}
function hostRemote(side,a){if(R.mode!=='host'||!a)return;if(a.kind==='key'){if(/^[1-7]$/.test(a.key)){window.S7VersusBattle.performAction({type:'select',side,index:Number(a.key)-1});return}if(side==='zombie'&&(a.key==='v'||a.key==='V')){window.S7VersusBattle.performAction({type:'toggleGuaranteed',side:'zombie'});return}if(side==='plant'&&(a.key==='q'||a.key==='Q')){window.S7VersusBattle.state.shovelMode=true;return}}
 if(a.kind==='pointer'){const nx=Number(a.nx),ny=Number(a.ny);if(!Number.isFinite(nx)||!Number.isFinite(ny))return;const H=innerHeight,W=innerWidth;const cardList=window.S7VersusBattle.cardsFor(side);if(ny>(H-116)/H){const y=ny*H;const rowTop=y>H-61?H-58:H-112;const maxW=Math.min(W-20,900),cardW=Math.max(72,Math.min(120,(maxW-10)/Math.max(1,cardList.length))),idx=Math.floor((nx*W-10)/cardW);if(idx>=0&&idx<cardList.length){window.S7VersusBattle.performAction({type:'select',side,index:idx});return}if(side==='zombie'&&nx>.78&&y<H-64){window.S7VersusBattle.performAction({type:'toggleGuaranteed',side:'zombie'});return}}
 const rect=canvas.getBoundingClientRect();if(side==='plant'&&window.S7VersusBattle.state.shovelMode){const cx=rect.left+nx*rect.width,cy=rect.top+ny*rect.height;const gx=(cx-rect.left)/rect.width,gy=(cy-rect.top)/rect.height,row=Math.max(0,Math.min(4,Math.floor((gy-(layout.y/innerHeight))/(layout.cell/innerHeight)))),col=Math.max(0,Math.min(8,Math.floor((gx-(layout.x/innerWidth))/(layout.cell/innerWidth))));window.S7VersusBattle.performAction({type:'shovel',side:'plant',row,col});window.S7VersusBattle.state.shovelMode=false;return}const act=window.S7VersusBattle.actionFromPointer(side,rect.left+nx*rect.width,rect.top+ny*rect.height,rect);window.S7VersusBattle.performAction(act)}}
function handle(m){if(!m)return;if(m.type==='versusFrame'&&R.mode==='guest'){if((m.seq||0)<=R.lastFrame)return;R.lastFrame=m.seq;drawFrame(m.data);return}if(m.type==='versusRemoteInput'&&R.mode==='host'){hostRemote(m.side,m.action);return}if(m.type==='versusProbeToHost'&&R.mode==='host'){send({type:'versusProbeAck',to:m.from,probeId:m.probeId,sentAt:m.sentAt});return}if(m.type==='versusProbeAck'&&R.mode==='guest'){const t=R.probeMap.get(m.probeId);if(t!=null){const rtt=performance.now()-t;R.probeMap.delete(m.probeId);meter(rtt/10)}return}if(m.type==='versusEnded'){stop();return}if(m.type==='disconnected'||m.type==='reconnecting')$('versusConnectionNotice')?.classList.remove('hidden')}
function stop(){if(R.frameTimer)clearInterval(R.frameTimer);if(R.probeTimer)clearInterval(R.probeTimer);R.frameTimer=R.probeTimer=0;R.mode=null;R.probeMap.clear()}
document.addEventListener('DOMContentLoaded',()=>{$('versusGuestStreamCanvas')?.addEventListener('pointerdown',sendPointer);canvas?.addEventListener('pointerdown',ev=>{if(R.mode!=='host')return;const r=canvas.getBoundingClientRect();hostRemote(R.side,{kind:'pointer',nx:(ev.clientX-r.left)/r.width,ny:(ev.clientY-r.top)/r.height})});window.addEventListener('keydown',sendKey);window.s7WSOn?.('message',handle);window.s7WSOn?.('disconnected',()=>{$('versusConnectionNotice')?.classList.remove('hidden')});window.s7WSOn?.('connected',()=>{$('versusConnectionNotice')?.classList.add('hidden')})});
window.S7VersusRealtime={startHost,startGuest,stop,handle};
})();
