const fs=require('fs'), path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
const html=read('index.html');
const sim=read('src/js/50_plant_simulation.js');
const combat=read('src/js/51_damage_combat.js');
const actions=read('src/js/92_s7_plant_actions.js');
const render=read('src/js/70_rendering.js');
const mp=read('src/js/96_battle_mode.js');
const server=read('server/server.js');
const tunnel=read('src/js/95_s7_home_tunnel_transport.js');
ok(html.includes('S丐版 1.8.0'), 'HTML version not 1.8.0');
ok(mp.includes('GAME_VERSION = "1.8.0"'), 'client multiplayer version not 1.8.0');
ok(server.includes('const SERVER_VERSION = "1.8.0"') && server.includes('serverVersion: SERVER_VERSION'), 'home tunnel server version not 1.8.0');
ok(tunnel.includes('this.gameVersion="1.8.0"'), 'home tunnel client default version not 1.8.0');
ok(sim.includes('立即向右弹飞1.5格') && sim.includes('S7_KNOCKBACK_DURATION'), 'v1.7.6 umbrella immediate knockback/CD lock missing');
ok(combat.includes('z.type === "bobsledSled"') && combat.includes('地刺王击退变种车辆'), 'v1.7.7 spikerock bobsled support missing');
ok(actions.includes('暗影地刺击退变种车辆') && actions.includes('z.type === "bobsledSled"'), 'v1.7.7 shadow-spike bobsled handling missing');
ok(render.includes('if (e && entityTextVisible)'), 'v1.7.8 element labels do not obey text toggle');
ok(tunnel.includes('serverOnline') && tunnel.includes('serverstatus') && tunnel.includes('__tunnel==="welcome"'), '2-server tunnel observability missing');
console.log('V1.7.8 SYNC REGRESSION PASS');
