"use strict";
const assert=require("assert"), fs=require("fs"), vm=require("vm");
const PLANTS={ twinSunflower:{}, sunflower:{}, sunshroom:{}, p0:{},p1:{},p2:{},p3:{},p4:{} };
const ZOMBIES={}; for(let i=0;i<8;i++)ZOMBIES[`z${i}`]={threat:1};
const store=new Map();
const ctx={console,PLANTS,ZOMBIES,ZOMBIE_KEYS:Object.keys(ZOMBIES),Date,Math,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}}; ctx.globalThis=ctx;
vm.createContext(ctx);
for(const f of ["src/js/22_versus_feature_profiles.js","src/js/25_versus_balance_format.js","src/js/26_versus_balance_telemetry.js"])vm.runInContext(fs.readFileSync(f,"utf8"),ctx);
const T=ctx.S7VersusBalanceTelemetry;
let m=T.createMatch({meta:{bpEnabled:false,totalSlots:6,combatSlots:5,firstPicker:"zombie",alternating:true},draft:{plantCards:["sunflower","p0","p1","p2","p3"],zombieCards:["z0","z1","z2","z3","z4"]}});
assert.strictEqual(m.meta.telemetryClass,"strength_truth");
assert.strictEqual(m.draft.plantEconomyCore,"twinSunflower");
T.recordCardUse(m,"plant","p0",{resourceCost:100,time:3,lane:1});
T.recordCardEffect(m,"plant","p0",{damage:120,objectiveDamage:20,kills:1});
T.recordEconomy(m,"plant",{generated:25,spent:100,current:75});
T.finishMatch(m,{winner:"plant",durationSeconds:420,targetsKilled:3});
assert.strictEqual(m.cardStats.plant.p0.damage,120);
assert(T.saveLocal(m));
assert.strictEqual(T.loadLocal().length,1);
let bp=T.createMatch({meta:{bpEnabled:true,totalSlots:6,combatSlots:5}});
assert.strictEqual(bp.meta.telemetryClass,"bp_resilience");
console.log("Versus balance telemetry tests: PASS");
